# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Combine
version:      4.003
version_from: Combine/Config.pm
installdirs:  site
requires:
    Algorithm::SVMLight:           0
    Compress::Zlib:                0
    Config::General:               0
    DBD::mysql:                    0
    DBI:                           0
    Digest::MD5:                   0
    Encode:                        0
    Geo::IP:                       0
    Getopt::Long:                  0
    HTML::Entities:                0
    HTML::Tidy:                    1.06
    HTML::TokeParser:              0
    HTTP::Date:                    0
    HTTP::Request:                 0
    HTTP::Status:                  0
    Image::ExifTool:               0
    Lingua::Identify:              0
    Lingua::Stem:                  0
    LWP::UserAgent:                0
    MIME::Base64:                  0
    Net::hostent:                  0
    URI:                           0
    XML::LibXML:                   0
    XML::LibXSLT:                  0
    XML::Parser:                   0
    ZOOM:                          1.2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
